// Catalog of live-data intents answered by the deterministic live services (Basis, ABAP, Security, BW, TM),
// each with real example phrasings. Used to map free-form questions that no keyword classifier recognised.
export type LiveModule = 'BASIS' | 'ABAP' | 'SECURITY' | 'BW' | 'TM';
export type LiveIntentEntry = { module: LiveModule; intent: string; examples: string[] };

export const LIVE_INTENT_CATALOG: LiveIntentEntry[] = [
  { module: 'BASIS', intent: 'ALERTS', examples: ["Which SAP systems have critical alerts?"] },
  { module: 'BASIS', intent: 'RESPONSE_TIME', examples: ["Which system has the highest response time?", "Which transactions have the highest response time?"] },
  { module: 'BASIS', intent: 'OVERLOADED', examples: ["Which application server is overloaded?"] },
  { module: 'BASIS', intent: 'ENQUEUE', examples: ["Are there any enqueue or lock issues?", "Is the enqueue server raising alerts?"] },
  { module: 'BASIS', intent: 'TOP_PROBLEMS', examples: ["Show the top five technical problems affecting users."] },
  { module: 'BASIS', intent: 'FIX_FIRST', examples: ["What should the Basis team fix first today?"] },
  { module: 'BASIS', intent: 'JOBS_FAILED_OVERNIGHT', examples: ["Which jobs failed overnight?"] },
  { module: 'BASIS', intent: 'JOB_WHY', examples: ["Why did job Z_MONTH_END fail?"] },
  { module: 'BASIS', intent: 'JOBS_LONG_RUNNING', examples: ["Show long-running background jobs."] },
  { module: 'BASIS', intent: 'JOBS_DELAYED', examples: ["Which jobs are delayed?"] },
  { module: 'BASIS', intent: 'JOBS_NOT_STARTED', examples: ["Which critical jobs did not start?"] },
  { module: 'BASIS', intent: 'JOBS_RUNTIME_EXCEEDED', examples: ["Which jobs are exceeding their normal runtime?"] },
  { module: 'BASIS', intent: 'JOBS_TONIGHT', examples: ["Show jobs scheduled for tonight."] },
  { module: 'BASIS', intent: 'JOBS_RESTARTABLE', examples: ["Which failed jobs can safely be restarted?"] },
  { module: 'BASIS', intent: 'JOB_RESTART', examples: ["Restart this failed job after validation."] },
  { module: 'BASIS', intent: 'JOBS_SLA', examples: ["Predict which jobs are likely to miss their SLA."] },
  { module: 'ABAP', intent: 'ST22_LIST', examples: ["Show today's ST22 dumps."] },
  { module: 'BASIS', intent: 'DUMPS_REPEATED', examples: ["Which ABAP dumps are occurring repeatedly?"] },
  { module: 'ABAP', intent: 'DUMP_EXPLAIN', examples: ["Explain this ST22 dump in plain English."] },
  { module: 'BASIS', intent: 'SYSLOG', examples: ["Show critical SM21 system log errors."] },
  { module: 'BASIS', intent: 'ERRORS_AFTER_TRANSPORT', examples: ["Which errors started after the latest transport?"] },
  { module: 'BASIS', intent: 'UPDATE_FAILURES', examples: ["Show update failures from SM13."] },
  { module: 'BASIS', intent: 'ERRORS_BUSINESS', examples: ["Which technical errors are impacting business transactions?"] },
  { module: 'BASIS', intent: 'CORRELATE', examples: ["Correlate dumps, jobs, and transports from the last four hours."] },
  { module: 'BASIS', intent: 'ROOT_CAUSE_TODAY', examples: ["What is the most likely root cause of today's errors?"] },
  { module: 'BASIS', intent: 'IMMEDIATE_ACTION', examples: ["Which errors require immediate action?"] },
  { module: 'BASIS', intent: 'WHY_SLOW', examples: ["Why is SAP running slowly?"] },
  { module: 'BASIS', intent: 'EXPENSIVE_TX', examples: ["Show the most expensive SAP transactions today."] },
  { module: 'BASIS', intent: 'WP_STUCK', examples: ["Which work processes are stuck?"] },
  { module: 'BASIS', intent: 'RESOURCE_CONSUMERS', examples: ["Which users or programs are consuming the most resources?"] },
  { module: 'BASIS', intent: 'WP_UTIL', examples: ["Show work process utilization across servers."] },
  { module: 'BASIS', intent: 'MEMORY', examples: ["Are there memory bottlenecks?"] },
  { module: 'BASIS', intent: 'LAYER_ANALYSIS', examples: ["Is the problem in SAP, HANA, network, or custom ABAP?"] },
  { module: 'BASIS', intent: 'COMPARE_DAYS', examples: ["Compare today's performance with yesterday."] },
  { module: 'BASIS', intent: 'CAPACITY', examples: ["Predict when system capacity could become critical."] },
  { module: 'BASIS', intent: 'USERS_LOCKED', examples: ["Which users are locked?"] },
  { module: 'BASIS', intent: 'FAILED_LOGINS', examples: ["Show failed login attempts."] },
  { module: 'BASIS', intent: 'TECH_USER_AUTH', examples: ["Which technical users have authentication problems?"] },
  { module: 'BASIS', intent: 'RFC_FAILING', examples: ["Which RFC destinations are failing?"] },
  { module: 'BASIS', intent: 'SM58', examples: ["Show queued transactions in SM58."] },
  { module: 'BASIS', intent: 'QRFC', examples: ["Show inbound and outbound qRFC problems."] },
  { module: 'BASIS', intent: 'CERT_EXPIRY', examples: ["Which certificates expire within the next 30 days?"] },
  { module: 'BASIS', intent: 'INTERFACES_DOWN', examples: ["Which interfaces are currently unavailable?"] },
  { module: 'BASIS', intent: 'PRIVILEGED', examples: ["Which privileged accounts require review?", "Show dormant privileged accounts."] },
  { module: 'BASIS', intent: 'AUDIT_RISKS', examples: ["Show Basis-related audit risks."] },
  { module: 'ABAP', intent: 'EXPLAIN_RECENT', examples: ["Explain what this ABAP program does."] },
  { module: 'ABAP', intent: 'TABLE_UPDATERS', examples: ["Which programs update this custom table?"] },
  { module: 'ABAP', intent: 'DUPLICATES', examples: ["Find duplicate logic across Z programs."] },
  { module: 'ABAP', intent: 'RISK', examples: ["Which custom objects are highest risk?"] },
  { module: 'ABAP', intent: 'DUMP_WHY', examples: ["Why did this ABAP program dump?"] },
  { module: 'ABAP', intent: 'DUMP_LINE', examples: ["Find the line of code causing the error."] },
  { module: 'ABAP', intent: 'ITAB_EMPTY', examples: ["Why is this internal table empty?"] },
  { module: 'ABAP', intent: 'SELECT_NO_DATA', examples: ["Why is this SELECT returning no data?"] },
  { module: 'ABAP', intent: 'BAPI_FAIL', examples: ["Why is this BAPI call failing?"] },
  { module: 'ABAP', intent: 'IDOC_FAIL', examples: ["Why is this IDoc processing program failing?"] },
  { module: 'ABAP', intent: 'JOB_TERM', examples: ["Why is this background job terminating?"] },
  { module: 'ABAP', intent: 'PROGRAM_ERRORS', examples: ["Show recent errors related to this program."] },
  { module: 'ABAP', intent: 'DEFECT_FIX', examples: ["Recommend the safest fix for this defect."] },
  { module: 'ABAP', intent: 'SLOWEST', examples: ["Which custom ABAP programs are slowest?"] },
  { module: 'ABAP', intent: 'SELECT_PERF', examples: ["Find SELECT statements causing performance problems."] },
  { module: 'ABAP', intent: 'DB_TIME', examples: ["Which custom reports consume the most database time?"] },
  { module: 'ABAP', intent: 'ANALYZE_SQL', examples: ["Analyze this SQL statement for HANA performance."] },
  { module: 'ABAP', intent: 'OPTIMIZE', examples: ["Recommend how to optimize this program."] },
  { module: 'ABAP', intent: 'RUNTIME_COMPARE', examples: ["Compare runtime before and after this change."] },
  { module: 'ABAP', intent: 'S4_COMPAT', examples: ["Which custom programs are not S/4HANA compatible?"] },
  { module: 'ABAP', intent: 'OBSOLETE', examples: ["Show code using obsolete tables or transactions."] },
  { module: 'ABAP', intent: 'SIMPLIFIED', examples: ["Find custom code affected by simplified data models."] },
  { module: 'ABAP', intent: 'CDS_REPLACE', examples: ["Which SELECT statements should be replaced with CDS views?"] },
  { module: 'ABAP', intent: 'FAIL_AFTER_MIGRATION', examples: ["Which custom objects will fail after S/4HANA migration?"] },
  { module: 'ABAP', intent: 'ATC', examples: ["Analyze ATC findings for this package."] },
  { module: 'SECURITY', intent: 'ACTIVE_USERS', examples: ["Show all active users in PRD."] },
  { module: 'SECURITY', intent: 'DORMANT_USERS', examples: ["Which users have not logged in for 90 days?"] },
  { module: 'SECURITY', intent: 'USERS_CREATED', examples: ["Show users created this week."] },
  { module: 'SECURITY', intent: 'PWD_EXPIRED', examples: ["Which users have expired passwords?"] },
  { module: 'SECURITY', intent: 'TERMINATED_ACCESS', examples: ["Which users have access after their termination date?"] },
  { module: 'SECURITY', intent: 'MULTI_DIALOG', examples: ["Show users with multiple dialog accounts."] },
  { module: 'SECURITY', intent: 'TECH_INTERACTIVE', examples: ["Which service or technical users are interactive?"] },
  { module: 'SECURITY', intent: 'USERS_BY_ORG', examples: ["Show users by company code, plant, or business unit."] },
  { module: 'SECURITY', intent: 'ACCOUNTS_REVIEW', examples: ["Which user accounts need immediate review?"] },
  { module: 'SECURITY', intent: 'USER_ROLES', examples: ["What roles does User ABC have?"] },
  { module: 'SECURITY', intent: 'TCODE_ACCESS', examples: ["Why does this user have access to transaction VA02?", "Which roles provide access to FB60?"] },
  { module: 'SECURITY', intent: 'SAP_ALL', examples: ["Show users with SAP_ALL."] },
  { module: 'SECURITY', intent: 'SAP_NEW', examples: ["Show users with SAP_NEW."] },
  { module: 'SECURITY', intent: 'CRITICAL_AUTH', examples: ["Which roles contain critical authorization objects?"] },
  { module: 'SECURITY', intent: 'COMPOSITE', examples: ["Show composite roles assigned to this user."] },
  { module: 'SECURITY', intent: 'ROLES_CHANGED', examples: ["Which roles were changed recently?"] },
  { module: 'SECURITY', intent: 'NEW_ACCESS', examples: ["Which users received new production access this week?"] },
  { module: 'SECURITY', intent: 'COMPARE_USERS', examples: ["Compare this user's access with another user in the same job role."] },
  { module: 'SECURITY', intent: 'SOD_ALL', examples: ["Show all current SoD conflicts."] },
  { module: 'SECURITY', intent: 'SOD_RULE', examples: ["Which users can both create and pay vendors?", "Who can create purchase orders and approve them?"] },
  { module: 'SECURITY', intent: 'SOD_HIGH', examples: ["Which SoD violations are high risk?"] },
  { module: 'SECURITY', intent: 'MITIGATED', examples: ["Which conflicts have mitigating controls?"] },
  { module: 'SECURITY', intent: 'MITIGATION_EXPIRED', examples: ["Which mitigating controls have expired?"] },
  { module: 'SECURITY', intent: 'SOD_NEW', examples: ["Show new SoD conflicts introduced this week."] },
  { module: 'SECURITY', intent: 'SOD_ROLE_FIX', examples: ["Which role changes would remove the largest number of SoD risks?"] },
  { module: 'SECURITY', intent: 'FF_USERS', examples: ["Show all firefighter users."] },
  { module: 'SECURITY', intent: 'FF_ACTIVITY', examples: ["Who used firefighter access today?", "Show emergency-access activity from the last 24 hours."] },
  { module: 'SECURITY', intent: 'FF_USER_ACTIVITY', examples: ["What did User ABC do during firefighter access?"] },
  { module: 'SECURITY', intent: 'FF_UNREVIEWED', examples: ["Show unreviewed firefighter sessions."] },
  { module: 'SECURITY', intent: 'PRIV_SENSITIVE', examples: ["Which privileged users performed sensitive transactions?"] },
  { module: 'SECURITY', intent: 'FF_SHARED', examples: ["Which firefighter IDs are assigned to too many users?"] },
  { module: 'SECURITY', intent: 'FF_NO_APPROVAL', examples: ["Which emergency-access sessions lacked approval?"] },
  { module: 'SECURITY', intent: 'PRIV_FIN', examples: ["Show privileged actions affecting finance or payroll."] },
  { module: 'SECURITY', intent: 'FF_INVESTIGATE', examples: ["Which emergency-access activities require investigation?"] },
  { module: 'SECURITY', intent: 'AUTH_FAILURES', examples: ["Which users are generating repeated authorization failures?", "Show critical SU53 failures."] },
  { module: 'SECURITY', intent: 'SENSITIVE_FIN', examples: ["Which users accessed sensitive financial data today?"] },
  { module: 'SECURITY', intent: 'ROLE_CHANGES_PROD', examples: ["Show role changes made directly in production."] },
  { module: 'SECURITY', intent: 'EXCESSIVE', examples: ["Which users have excessive access compared with their peers?"] },
  { module: 'SECURITY', intent: 'CONTROLS', examples: ["Which security controls are currently failing?"] },
  { module: 'SECURITY', intent: 'TOP_RISKS', examples: ["What are our highest SAP security risks today?"] },
  { module: 'SECURITY', intent: 'REMEDIATE', examples: ["What should the security team remediate first?"] },
  { module: 'BW', intent: 'PLANT_BUDGET', examples: ["Which plants are exceeding their operating budget?"] },
  { module: 'BW', intent: 'PLAN_ACTUAL', examples: ["Show actual versus plan for this quarter."] },
  { module: 'BW', intent: 'CEO', examples: ["How is the company performing today?"] },
  { module: 'BW', intent: 'BW_CHAINS', examples: ["Show BW process chains that failed overnight."] },
  { module: 'BW', intent: 'BW_LOADS_DELAYED', examples: ["Which BW data loads are delayed?"] },
  { module: 'BW', intent: 'BW_DTP', examples: ["Why did this DTP fail?"] },
  { module: 'BW', intent: 'BW_ADSO_LOAD', examples: ["Which ADSOs have not loaded successfully?"] },
  { module: 'BW', intent: 'BW_REQ_ERR', examples: ["Show requests with errors."] },
  { module: 'BW', intent: 'BW_STALE', examples: ["Which InfoProviders have stale data?"] },
  { module: 'BW', intent: 'BW_DEPEND', examples: ["Which BW objects depend on this ADSO?"] },
  { module: 'BW', intent: 'ETL_TODAY', examples: ["Show today's source-system loads."] },
  { module: 'BW', intent: 'ETL_EXTRACTORS', examples: ["Which extractors failed?"] },
  { module: 'BW', intent: 'ETL_MISSING', examples: ["What data is missing from today's load?"] },
  { module: 'BW', intent: 'ETL_RECON', examples: ["Compare source record count with BW record count."] },
  { module: 'BW', intent: 'ETL_DELTA', examples: ["Which delta loads are incomplete?"] },
  { module: 'BW', intent: 'ETL_DUP', examples: ["Show duplicate records detected during loading."] },
  { module: 'BW', intent: 'ETL_TRANSF', examples: ["Which transformations generated errors?"] },
  { module: 'BW', intent: 'ETL_SALES_MISSING', examples: ["Why are yesterday's sales missing from BW?"] },
  { module: 'BW', intent: 'ETL_DURATION', examples: ["Show data-load duration trends."] },
  { module: 'BW', intent: 'ETL_SLA', examples: ["Predict which nightly loads may miss the reporting SLA."] },
  { module: 'BW', intent: 'PROD_VARIANCE', examples: ["Show production variance by plant."] },
  { module: 'BW', intent: 'DS_SPACES', examples: ["Show the available Datasphere spaces."] },
  { module: 'BW', intent: 'DS_MODELS', examples: ["Which analytic models are exposed for consumption?"] },
  { module: 'BW', intent: 'DS_FIN', examples: ["Show datasets available in the Finance space."] },
  { module: 'BW', intent: 'DS_S4DEP', examples: ["Which Datasphere models depend on S/4HANA?"] },
  { module: 'BW', intent: 'DS_LINEAGE', examples: ["Show data lineage for this analytical model."] },
  { module: 'BW', intent: 'DS_STALE', examples: ["Which data products are stale?"] },
  { module: 'BW', intent: 'DS_CONN', examples: ["Which Datasphere connections are failing?"] },
  { module: 'BW', intent: 'DS_USERS', examples: ["Show users consuming this analytical model."] },
  { module: 'BW', intent: 'DS_PERF', examples: ["Which models have performance issues?"] },
  { module: 'TM', intent: 'FU_TODAY', examples: ["Show all freight units created today."] },
  { module: 'TM', intent: 'FU_UNPLANNED', examples: ["Which freight units are not yet planned?"] },
  { module: 'TM', intent: 'SHIP_TODAY', examples: ["Show shipments scheduled for today."] },
  { module: 'TM', intent: 'TO_DELAYED', examples: ["Which transportation orders are delayed?"] },
  { module: 'TM', intent: 'NO_CARRIER', examples: ["Which loads are not assigned to a carrier?"] },
  { module: 'TM', intent: 'MISSING_EQUIP', examples: ["Which shipments are missing equipment?"] },
  { module: 'TM', intent: 'FO_BY_LOC', examples: ["Show freight orders by plant, shipping point, or region."] },
  { module: 'TM', intent: 'AT_RISK', examples: ["Which shipments are at risk of missing delivery dates?"] },
  { module: 'TM', intent: 'WORKLOAD', examples: ["Show today's transportation workload."] },
  { module: 'TM', intent: 'ISSUES', examples: ["What transportation issues need immediate attention?"] },
  { module: 'TM', intent: 'CARRIER_BEST', examples: ["Which carriers are performing best?"] },
  { module: 'TM', intent: 'CARRIER_DELAY_RATE', examples: ["Which carriers have the highest delay rate?"] },
  { module: 'TM', intent: 'CARRIER_COMPARE', examples: ["Compare carriers by cost and service level."] },
  { module: 'TM', intent: 'CARRIER_FOR_SHIPMENT', examples: ["Which carrier should we use for this shipment?"] },
  { module: 'TM', intent: 'CARRIER_CAPACITY', examples: ["Which carriers have available capacity today?"] },
  { module: 'TM', intent: 'CARRIER_REJECT', examples: ["Which carriers are rejecting tenders?"] },
  { module: 'TM', intent: 'CARRIER_ACCEPT', examples: ["Show carrier acceptance rates."] },
  { module: 'TM', intent: 'CARRIER_LATE', examples: ["Which carriers are consistently late?"] },
  { module: 'TM', intent: 'CLAIMS', examples: ["Which carriers have the highest freight claims?"] },
  { module: 'TM', intent: 'ALT_CARRIER', examples: ["Recommend alternate carriers for delayed shipments."] },
  { module: 'TM', intent: 'COST_TODAY', examples: ["Show transportation cost for today's shipments."] },
  { module: 'TM', intent: 'LANE_COST', examples: ["Which lanes have the highest freight cost?"] },
  { module: 'TM', intent: 'PLAN_VS_ACTUAL', examples: ["Compare planned freight cost with actual cost."] },
  { module: 'TM', intent: 'RATE_INCREASE', examples: ["Which carriers have increased rates recently?"] },
  { module: 'TM', intent: 'SPEND_CARRIER', examples: ["Show transportation spend by carrier."] },
  { module: 'TM', intent: 'SPEND_LANE', examples: ["Show transportation spend by lane."] },
  { module: 'TM', intent: 'COST_EXCEEDED', examples: ["Which shipments exceeded expected freight cost?"] },
  { module: 'TM', intent: 'SAVINGS', examples: ["Find freight cost-saving opportunities."] },
  { module: 'TM', intent: 'ACCESSORIAL', examples: ["Which routes have excessive accessorial charges?"] },
  { module: 'TM', intent: 'SPEND_FORECAST', examples: ["Forecast transportation spend for this month."] },
  { module: 'TM', intent: 'NOT_DEPARTED', examples: ["Which shipments have not departed?"] },
  { module: 'TM', intent: 'TRUCKS_LATE', examples: ["Which trucks are late arriving at the warehouse?"] },
  { module: 'TM', intent: 'IN_TRANSIT', examples: ["Show shipments currently in transit."] },
  { module: 'TM', intent: 'MISSED_PICKUP', examples: ["Show missed pickup appointments."] },
  { module: 'TM', intent: 'EXEC_EXCEPTIONS', examples: ["Which freight orders have execution exceptions?"] },
  { module: 'TM', intent: 'WAITING_DOCK', examples: ["Which shipments are waiting at the dock?"] },
  { module: 'TM', intent: 'POD', examples: ["Show proof-of-delivery exceptions."] },
  { module: 'TM', intent: 'DETENTION', examples: ["Which shipments have detention or demurrage risk?"] },
  { module: 'TM', intent: 'CUSTOMERS_AFFECTED', examples: ["Which customers are affected by transportation delays?"] },
  { module: 'TM', intent: 'BEST_ROUTE', examples: ["What is the best route for this shipment?"] },
  { module: 'TM', intent: 'CONSOLIDATE', examples: ["Can we consolidate these deliveries into one load?"] },
  { module: 'TM', intent: 'UNDERUTILIZED', examples: ["Which loads are underutilized?"] },
  { module: 'TM', intent: 'TRAILER_UTIL', examples: ["Show trailer utilization."] },
  { module: 'TM', intent: 'LANES_CONSOLIDATE', examples: ["Which lanes should be consolidated?"] },
  { module: 'TM', intent: 'EMPTY_MILES', examples: ["Can we reduce empty miles?"] },
  { module: 'TM', intent: 'WH_DELAYS', examples: ["Which warehouses are causing transportation delays?"] },
  { module: 'TM', intent: 'CAPACITY_SHORTAGE', examples: ["Predict tomorrow's transportation capacity shortage."] },
  { module: 'TM', intent: 'OPTIMAL_PLAN', examples: ["Recommend the optimal transportation plan."] },
  { module: 'TM', intent: 'REDUCE_COST', examples: ["What actions can reduce logistics cost today?"] },
  { module: 'BASIS', intent: 'KERNEL_VERSION', examples: ["give me the current kernel version", "What SAP release and database version are we running?"] },
  { module: 'BASIS', intent: 'LOCK_ENTRIES', examples: ["show current locks", "Who is holding or blocking objects right now?", "Which tables or records are locked and by whom (SM12)?"] },
  { module: 'BASIS', intent: 'JOBS_FAILED', examples: ["Which jobs failed?"] },
  { module: 'ABAP', intent: 'CUSTOM_TABLES', examples: ["show me custom tables"] },
];

export function liveIntentCatalogPrompt(): string {
  return LIVE_INTENT_CATALOG.map(e => `${e.module}:${e.intent} | ${e.examples.join(' | ')}`).join('\n');
}

export function resolveLiveIntent(module: string, intent: string): LiveIntentEntry | null {
  return LIVE_INTENT_CATALOG.find(e => e.module === String(module || '').toUpperCase() && e.intent === String(intent || '').toUpperCase()) || null;
}