// PP50 diagnostic — live tests the 50 natural-language PP questions across 5 categories.
const APP_URL = 'http://localhost:3000/api/gemini/query';
async function callChat(question) {
  const res = await fetch(APP_URL, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ query: question, userRole: 'Functional Consultant', history: [], backendTarget: 'BOTH' }) });
  const raw = await res.text();
  const lines = raw.split('\n').map(s => s.trim()).filter(Boolean);
  for (const line of lines.reverse()) {
    try { const parsed = JSON.parse(line); if (parsed?.type === 'result') return { text: parsed.text || '', toolCount: (parsed.toolResults || []).length }; } catch {}
  }
  return { text: '', toolCount: 0 };
}

const questions = [
  // Production Planning (10)
  "What's today's production schedule?",
  "Show me all production orders that are delayed.",
  "Which production orders are at risk of missing their delivery date?",
  "What should we manufacture today based on current orders?",
  "Show this week's production plan.",
  "Which production lines have the highest workload today?",
  "Compare today's production output with yesterday.",
  "What's our production efficiency by plant?",
  "Show me products that are behind schedule.",
  "Which plants have idle capacity right now?",
  // MRP & Material Planning (10)
  "Run MRP for Plant 1000.",
  "Which materials will run out within 7 days?",
  "Show me shortages affecting production.",
  "Which planned orders need to be converted to production orders?",
  "Show all MRP exceptions.",
  "What purchase requisitions were generated by MRP today?",
  "Show materials with excess inventory.",
  "Which components are causing production delays?",
  "Recommend inventory optimization for production materials.",
  "Which materials are critical and need immediate procurement?",
  // Production Orders (10)
  "Show all open production orders.",
  "Which production orders are not yet released?",
  "Show production orders that are partially confirmed.",
  "Close all completed production orders.",
  "Which orders are waiting for components?",
  "Why is Production Order 1000000 delayed?",
  "Who is responsible for Production Order 1000000?",
  "Show production order progress by operation.",
  "Which orders exceeded their planned costs?",
  "Show today's production confirmations.",
  // Capacity Planning (10)
  "Which work centers are overloaded?",
  "Which work centers are underutilized?",
  "Show machine utilization this week.",
  "Predict next week's capacity bottlenecks.",
  "Recommend production rescheduling to avoid delays.",
  "Which work center is causing production delays?",
  "Simulate adding an extra production shift.",
  "What happens if demand increases by 20%?",
  "Recommend how to balance workloads across plants.",
  "Identify available production capacity.",
  // BOM & Routing (10)
  "Show the BOM for Material SG22.",
  "Which BOMs were changed recently?",
  "Compare BOM versions for SG22 and SG21.",
  "Show obsolete components in our BOMs.",
  "Display the routing for Material SG22.",
  "Which routing operations consume the most time?",
  "Show missing BOM components.",
  "Which engineering changes are affecting production?",
  "Recommend BOM optimization opportunities.",
  "Which products share common components?",
];

async function ask(query) {
  try {
    const r = await callChat(query);
    return { toolCount: r.toolCount, text: (r.text || '').slice(0, 220).replace(/\n/g, ' ') };
  } catch (e) {
    return { toolCount: 0, text: String(e).slice(0, 200) };
  }
}

let pass = 0, fail = 0;
for (let i = 0; i < questions.length; i++) {
  const q = questions[i];
  const r = await ask(q);
  const isUnavailableError = /LIVE_SAP_UNAVAILABLE|fetch failed|ENOTFOUND/i.test(r.text);
  const status = !isUnavailableError && (r.toolCount > 0 || (r.text && r.text.length > 30)) ? 'PASS' : 'FAIL';
  if (status === 'PASS') pass++; else fail++;
  console.log(`[${i + 1}/50] ${status} (tools=${r.toolCount}) :: ${q}`);
  console.log(`    -> ${r.text}`);
}
console.log(`\n=== PP50 RESULTS: ${pass} PASS / ${fail} FAIL / 50 total ===`);
